export const RECEIVE_TRENDING_GIFS = 'RECEIVE_TRENDING_GIFS';
export const REQUEST_TRENDING_GIFS = 'REQUEST_TRENDING_GIFS';
export const REQUEST_TRENDING_GIFS_FAILED = 'REQUEST_TRENDING_GIFS_FAILED';
export const REQUEST_SEARCH_GIFS = 'REQUEST_SEARCH_GIFS';
export const REQUEST_SEARCH_GIFS_FAILED = 'REQUEST_SEARCH_GIFS_FAILED';
export const RECEIVE_SEARCH_GIFS = 'RECEIVE_SEARCH_GIFS';
