export const RECEIVE_TRENDING_GIFS = 'RECEIVE_TRENDING_GIFS';
export const REQUEST_TRENDING_GIFS = 'REQUEST_TRENDING_GIFS';
export const REQUEST_TRENDING_GIFS_FAILED = 'REQUEST_TRENDING_GIFS_FAILED';
export const REFRESH_TRENDING_GIFS = 'REFRESH_TRENDING_GIFS';

export const REQUEST_SEARCH_GIFS = 'REQUEST_SEARCH_GIFS';
export const REQUEST_SEARCH_GIFS_FAILED = 'REQUEST_SEARCH_GIFS_FAILED';
export const RECEIVE_SEARCH_GIFS = 'RECEIVE_SEARCH_GIFS';
export const CLEAR_SEARCH_GIFS = 'CLEAR_SEARCH_GIFS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
