export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const ENTER_TRENDING_MODE = 'ENTER_TRENDING_MODE';
export const ENTER_SEARCH_MODE = 'ENTER_SEARCH_MODE';
export const REQUEST_GIFS = 'REQUEST_GIFS';
export const RECEIVE_GIFS = 'RECEIVE_GIFS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
